In [1]:
import numpy as np
import pandas as pd

In [5]:
pd.__version__

'0.25.1'

In [6]:
data = pd.Series([0.25, 0.5, 0.75, 1])
data

0    0.25
1    0.50
2    0.75
3    1.00
dtype: float64

In [7]:
data.values

array([0.25, 0.5 , 0.75, 1.  ])

In [8]:
data.index

RangeIndex(start=0, stop=4, step=1)

In [10]:
data2 = np.arange(4)
data2

array([0, 1, 2, 3])

In [11]:
data = pd.Series([0.25, 0.5, 0.75, 1], 
                index = ['a', 'b', 'c', 'd'])
data

a    0.25
b    0.50
c    0.75
d    1.00
dtype: float64

In [39]:
population_dict = {'Taiwan': 2300,
                   'USA': 23000,
                   'XXX': 23223}
population_dict

{'Taiwan': 2300, 'USA': 23000, 'XXX': 23223}

In [40]:
population = pd.Series(population_dict)
population

Taiwan     2300
USA       23000
XXX       23223
dtype: int64

In [41]:
#dataframe
area_dict = {'Taiwan':3423423,'USA':452114,'XXX':50141}
area = pd.Series(area_dict)
area

Taiwan    3423423
USA        452114
XXX         50141
dtype: int64

In [42]:
states = pd.DataFrame({'population': population,
                      'area': area})
states

population     area
Taiwan        2300  3423423
USA          23000   452114
XXX          23223    50141

In [39]:
population_dict = {'Taiwan': 2300,
                   'USA': 23000,
                   'XXX': 23223}
population_dict

{'Taiwan': 2300, 'USA': 23000, 'XXX': 23223}

In [40]:
population = pd.Series(population_dict)
population

Taiwan     2300
USA       23000
XXX       23223
dtype: int64

In [41]:
#dataframe
area_dict = {'Taiwan':3423423,'USA':452114,'XXX':50141}
area = pd.Series(area_dict)
area

Taiwan    3423423
USA        452114
XXX         50141
dtype: int64

In [42]:
states = pd.DataFrame({'population': population,
                      'area': area})
states

population     area
Taiwan        2300  3423423
USA          23000   452114
XXX          23223    50141

In [30]:
population

Taiwan     2300
USA       23000
XXX       23223
dtype: int64

In [35]:
#用series建立
pd.DataFrame(population, columns=['population'])

population
Taiwan        2300
USA          23000
XXX          23223

In [34]:
#用字典的list建立
data = [{'a': i, 'b': 2 * i} for i in range(3)]
pd.DataFrame(data)

a  b
0  0  0
1  1  2
2  2  4

In [36]:
#用series字典建立
pd.DataFrame({'population':population, 'area': area})

population     area
Taiwan        2300  3423423
USA          23000   452114
XXX          23223    50141

In [112]:
#用np二維陣列建立
pd.DataFrame(np.random.rand(3,2), columns=['foo', 'bar'], index = ['a', 'b', 'c'])

foo       bar
a  0.724835  0.438976
b  0.611983  0.599910
c  0.060744  0.501184

In [117]:
#pd的index物件
ind = pd.Index([2, 6, 9, 10, 111])
ind

Int64Index([2, 6, 9, 10, 111], dtype='int64')

In [127]:
ind[1] = 1

TypeError: Index does not support mutable operations

In [128]:
indA = pd.Index([1,3,5,7,9])
indB = pd.Index([2,3,6,7,111])
indA & indB

Int64Index([3, 7], dtype='int64')

In [129]:
indA | indB

Int64Index([1, 2, 3, 5, 6, 7, 9, 111], dtype='int64')

In [6]:
#用dict方式查series
data = pd.Series([0.25, 0.5, 0.75, 1], index = ['a' , 'b', 'c', 'd'])
data.keys()

Index(['a', 'b', 'c', 'd'], dtype='object')

In [10]:
list(data.items())

[('a', 0.25), ('b', 0.5), ('c', 0.75), ('d', 1.0)]

In [12]:
data['e'] = 1.25
data

a    0.25
b    0.50
c    0.75
d    1.00
e    1.25
dtype: float64

In [14]:
#用dict方式查series
data2 = pd.Series([0.25, 0.5, 0.75, 1], index = [5, 2, 1, 8])
data2

5    0.25
2    0.50
1    0.75
8    1.00
dtype: float64

In [27]:
data2['5':'1']

TypeError: cannot do slice indexing on <class 'pandas.core.indexes.numeric.Int64Index'> with these indexers [5] of <class 'str'>

In [28]:
data['a':'c']

a    0.25
b    0.50
c    0.75
dtype: float64

In [30]:
data3 = pd.Series(['a', 'b', 'c'], index=[1, 3, 5])
data3

1    a
3    b
5    c
dtype: object

In [31]:
#明確索引
data3[1]

'a'

In [32]:
#隱晦索引
#不是顯示 index=1 ~ index=3 會混淆
data3[1:3]

3    b
5    c
dtype: object

In [34]:
#loc 參考到明確索引
data3.loc[1:3]

1    a
3    b
dtype: object

In [43]:
population_dict = {'Taiwan': 2300,
                   'USA': 23000,
                   'XXX': 23223}
population_dict

population = pd.Series(population_dict)
population

#dataframe
area_dict = {'Taiwan':3423423,'USA':452114,'XXX':50141}
area = pd.Series(area_dict)
area

states = pd.DataFrame({'population': population,
                      'area': area})
states

population     area
Taiwan        2300  3423423
USA          23000   452114
XXX          23223    50141

In [45]:
states['USA':'XXX']

population    area
USA       23000  452114
XXX       23223   50141

In [73]:
states.loc[:,'population':'area']

population     area
Taiwan        2300  3423423
USA          23000   452114
XXX          23223    50141

In [80]:
states.loc[:, 'population']

Taiwan     2300
USA       23000
XXX       23223
Name: population, dtype: int64

In [91]:
states['USA':'XXX']

population    area
USA       23000  452114
XXX       23223   50141

In [96]:
states[['area']]

area
Taiwan  3423423
USA      452114
XXX       50141

In [97]:
states['area']

Taiwan    3423423
USA        452114
XXX         50141
Name: area, dtype: int64

In [105]:
states.loc['XXX','area']

50141

In [106]:
#把dataframe當作二微陣列
states.values

array([[   2300, 3423423],
       [  23000,  452114],
       [  23223,   50141]], dtype=int64)

In [108]:
states.keys

<bound method NDFrame.keys of         population     area
Taiwan        2300  3423423
USA          23000   452114
XXX          23223    50141>

In [110]:
states.values[0]

array([   2300, 3423423], dtype=int64)

In [129]:
states.loc['Taiwan',:]

population       2300
area          3423423
Name: Taiwan, dtype: int64

In [135]:
states.loc[states['area'] > 100000, ['population', 'area']]

population     area
Taiwan        2300  3423423
USA          23000   452114

In [140]:
pd.DataFrame(states.loc[states.area > 100000, 'area'])

area
Taiwan  3423423
USA      452114

In [144]:
#numpy的function可以用在pandas
rng = np.random.RandomState(42)
ser = pd.Series(rng.randint(0, 10, 4))
ser

0    6
1    3
2    7
3    4
dtype: int32

In [147]:
df = pd.DataFrame(rng.randint(0, 10, (3, 4)), columns=['A', 'B', 'C', 'D'])
df

A  B  C  D
0  6  3  8  2
1  4  2  6  4
2  8  6  1  3

In [148]:
np.exp(ser)

0     403.428793
1      20.085537
2    1096.633158
3      54.598150
dtype: float64

In [150]:
#索引對齊
area2 = area.copy()
population2 = population.copy()

In [153]:
area2['Japan'] = 222222
area2

Taiwan    3423423
USA        452114
XXX         50141
Japan      222222
dtype: int64

In [154]:
area2 / population2

Japan             NaN
Taiwan    1488.444783
USA         19.657130
XXX          2.159110
dtype: float64

In [157]:
area2.index | population2.index

Index(['Japan', 'Taiwan', 'USA', 'XXX'], dtype='object')

In [158]:
A = pd.Series([2,4,6], index=[4,2,6])
B = pd.Series([5,5,7], index=[1,2,4])
A+B

1    NaN
2    9.0
4    9.0
6    NaN
dtype: float64

In [159]:
A.add(B, fill_value=0)

1    5.0
2    9.0
4    9.0
6    6.0
dtype: float64

In [160]:
list('AB')

['A', 'B']

In [186]:
A = pd.DataFrame(rng.randint(0, 20, (2, 2)), columns=list('AB'))
B = pd.DataFrame(rng.randint(0, 10, (3, 3)), columns=list('ABC'))
A + B

A     B   C
0   4.0   4.0 NaN
1  23.0  19.0 NaN
2   NaN   NaN NaN

In [187]:
fill = A.stack().mean()
A.add(B, fill_value=fill)

A      B      C
0   4.00   4.00  12.25
1  23.00  19.00  14.25
2  16.25  17.25  17.25

In [188]:
A.stack()

0  A     2
   B     4
1  A    14
   B    13
dtype: int32

In [231]:
#dataframe boradcasting
A = rng.randint(10, size=(3,4))
A

array([[6, 7, 2, 0],
       [3, 1, 7, 3],
       [1, 5, 5, 9]])

In [225]:
A - A[0]

array([[ 0,  0,  0,  0],
       [ 7,  6,  2,  2],
       [ 7,  4, -1,  6]])

In [237]:
df = pd.DataFrame(A,columns=list('QRST'))
df

Q  R  S  T
0  6  7  2  0
1  3  1  7  3
2  1  5  5  9

In [245]:
df - df.iloc[0]

Q  R  S  T
0  0  0  0  0
1 -3 -6  5  3
2 -5 -2  3  9

In [251]:
df.sub(df['R'], axis = 0)

Q  R  S  T
0 -1  0 -5 -7
1  2  0  6  2
2 -4  0  0  4

In [258]:
halfrow = df.iloc[0,::2]

In [259]:
df - halfrow

Q   R    S   T
0  0.0 NaN  0.0 NaN
1 -3.0 NaN  5.0 NaN
2 -5.0 NaN  3.0 NaN

In [29]:
#缺失值
a = np.array([1, 2, 3, None])
a

array([1, 2, 3, None], dtype=object)

In [30]:
b = pd.Series([1, 2, 3, None])
b

0    1.0
1    2.0
2    3.0
3    NaN
dtype: float64

In [31]:
c = np.array([1, 2, 3, np.nan])

In [32]:
d = pd.Series([1, 2, 3, np.nan])

In [33]:
a.sum()

TypeError: unsupported operand type(s) for +: 'int' and 'NoneType'

In [34]:
b.sum()

6.0

In [35]:
c.sum()

nan

In [36]:
d.sum()

6.0

In [ ]:
#NULL 操作

In [37]:
data = pd.Series([1, np.nan, 'hello', None])
data.isnull()

0    False
1     True
2    False
3     True
dtype: bool

In [38]:
data.notnull()

0     True
1    False
2     True
3    False
dtype: bool

In [39]:
data[data.notnull()]

0        1
2    hello
dtype: object

In [102]:
# Dataframe + dropna()
df = np.arange(9).reshape(3,3)
df = pd.DataFrame(df)
df.iloc[1,1] = None
df

0    1  2
0  0  1.0  2
1  3  NaN  5
2  6  7.0  8

In [103]:
df.dropna()

0    1  2
0  0  1.0  2
2  6  7.0  8

In [12]:
b = pd.Series([1, 2, 3, None])
b

0    1.0
1    2.0
2    3.0
3    NaN
dtype: float64

In [104]:
df[3] = np.nan
df

0    1  2   3
0  0  1.0  2 NaN
1  3  NaN  5 NaN
2  6  7.0  8 NaN

In [126]:
df.dropna(thresh=2)

0    1    2   3
0  0.0  1.0  2.0 NaN
1  3.0  NaN  5.0 NaN

SyntaxError: invalid syntax (<ipython-input-67-7c1b5e3ca714>, line 1)

In [106]:
df.iloc[2] = np.nan
df

0    1    2   3
0  0.0  1.0  2.0 NaN
1  3.0  NaN  5.0 NaN
2  NaN  NaN  NaN NaN

In [117]:
df

0    1    2   3
0  0.0  1.0  2.0 NaN
1  3.0  NaN  5.0 NaN
2  NaN  NaN  NaN NaN

In [112]:
df.dropna(axis=1,how='all')

0    1    2
0  0.0  1.0  2.0
1  3.0  NaN  5.0
2  NaN  NaN  NaN

In [127]:
#fillna()
data = pd.Series([1, np.nan, 2, None, 3], index=list("abcde"))
data

a    1.0
b    NaN
c    2.0
d    NaN
e    3.0
dtype: float64

In [129]:
data.fillna(0)

a    1.0
b    NaN
c    2.0
d    NaN
e    3.0
dtype: float64

In [130]:
data.fillna(method='ffill')

a    1.0
b    1.0
c    2.0
d    2.0
e    3.0
dtype: float64

In [133]:
data.fillna(np.mean(data))

a    1.0
b    2.0
c    2.0
d    2.0
e    3.0
dtype: float64

In [12]:
b = pd.Series([1, 2, 3, None])
b

0    1.0
1    2.0
2    3.0
3    NaN
dtype: float64

In [138]:
df

0    1    2   3
0  0.0  1.0  2.0 NaN
1  3.0  NaN  5.0 NaN
2  NaN  NaN  NaN NaN

In [137]:
df.fillna(method='ffill', axis=1)

0    1    2    3
0  0.0  1.0  2.0  2.0
1  3.0  3.0  5.0  5.0
2  NaN  NaN  NaN  NaN

In [139]:
df.fillna(method='ffill')

0    1    2   3
0  0.0  1.0  2.0 NaN
1  3.0  1.0  5.0 NaN
2  3.0  1.0  5.0 NaN

In [140]:
#階層式索引
import pandas as pd
import numpy as np

In [3]:
# bad way
index = [('California', 2000), ('California', 2010),
         ('New York', 2000), ('New York', 2010),
         ('Texas', 2000), ('Texas', 2010)]
population = [3335234, 5235423, 3453253, 
             4352542, 5346366, 2342344]
pop = pd.Series(population, index = index)
pop

(California, 2000)    3335234
(California, 2010)    5235423
(New York, 2000)      3453253
(New York, 2010)      4352542
(Texas, 2000)         5346366
(Texas, 2010)         2342344
dtype: int64

In [6]:
# good way
index = pd.MultiIndex.from_tuples(index)
index

MultiIndex([('California', 2000),
            ('California', 2010),
            (  'New York', 2000),
            (  'New York', 2010),
            (     'Texas', 2000),
            (     'Texas', 2010)],
           )

In [8]:
pop = pop.reindex(index)
pop

California  2000    3335234
            2010    5235423
New York    2000    3453253
            2010    4352542
Texas       2000    5346366
            2010    2342344
dtype: int64

In [27]:
pop['Texas']

2000    5346366
2010    2342344
dtype: int64

In [32]:
pop[:,2000]

California    3335234
New York      3453253
Texas         5346366
dtype: int64

In [36]:
pop_df = pop.unstack()
pop_df

2000     2010
California  3335234  5235423
New York    3453253  4352542
Texas       5346366  2342344

In [37]:
pop_df.stack()

California  2000    3335234
            2010    5235423
New York    2000    3453253
            2010    4352542
Texas       2000    5346366
            2010    2342344
dtype: int64

In [41]:
pop_df = pd.DataFrame({'total':pop, 'under18':[1323,2323,2343,4354,3424,4623]})
pop_df

total  under18
California 2000  3335234     1323
           2010  5235423     2323
New York   2000  3453253     2343
           2010  4352542     4354
Texas      2000  5346366     3424
           2010  2342344     4623

In [50]:
pd.DataFrame({'wtf':pop})

wtf
California 2000  3335234
           2010  5235423
New York   2000  3453253
           2010  4352542
Texas      2000  5346366
           2010  2342344

In [59]:
f_u18 = pop_df['under18'] / pop_df['total']
f_u18

California  2000    0.000397
            2010    0.000444
New York    2000    0.000678
            2010    0.001000
Texas       2000    0.000640
            2010    0.001974
dtype: float64

In [60]:
f_u18.unstack()

2000      2010
California  0.000397  0.000444
New York    0.000678  0.001000
Texas       0.000640  0.001974

In [80]:
pd.DataFrame(np.random.rand(4,2), index=[list('aabb'), list('1212')], columns=['data1','data2'])

data1     data2
a 1  0.735902  0.790589
  2  0.908292  0.570932
b 1  0.093688  0.402930
  2  0.156144  0.183086

In [82]:
# 不同 Multilndex 建構子
pd.MultiIndex.from_arrays([list('aabb'), list('1212')])

MultiIndex([('a', '1'),
            ('a', '2'),
            ('b', '1'),
            ('b', '2')],
           )

In [83]:
pd.MultiIndex.from_tuples([('a',1), ('b', 2)])

MultiIndex([('a', 1),
            ('b', 2)],
           )

In [88]:
pd.MultiIndex.from_product([['a','b'], [1, 2]])

MultiIndex([('a', 1),
            ('a', 2),
            ('b', 1),
            ('b', 2)],
           )

In [89]:
pd.MultiIndex(levels=[['a','b'], [1, 2]], labels = [[0, 0, 1, 1], [0,1,0,1]])

C:\Users\9Suser\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: FutureWarning: the 'labels' keyword is deprecated, use 'codes' instead
  """Entry point for launching an IPython kernel.


MultiIndex([('a', 1),
            ('a', 2),
            ('b', 1),
            ('b', 2)],
           )

In [90]:
pop

California  2000    3335234
            2010    5235423
New York    2000    3453253
            2010    4352542
Texas       2000    5346366
            2010    2342344
dtype: int64

In [104]:
pop.index.names = ['state', 'year']
pop

state       year
California  2000    3335234
            2010    5235423
New York    2000    3453253
            2010    4352542
Texas       2000    5346366
            2010    2342344
dtype: int64

In [105]:
pop_df

total  under18
state      year                  
California 2000  3335234     1323
           2010  5235423     2323
New York   2000  3453253     2343
           2010  4352542     4354
Texas      2000  5346366     3424
           2010  2342344     4623

In [109]:
index = pd.MultiIndex.from_product([[2013, 2014, 2015], [1,2,3,4,5,6,7,8,9,10,11,12]])
index

MultiIndex([(2013,  1),
            (2013,  2),
            (2013,  3),
            (2013,  4),
            (2013,  5),
            (2013,  6),
            (2013,  7),
            (2013,  8),
            (2013,  9),
            (2013, 10),
            (2013, 11),
            (2013, 12),
            (2014,  1),
            (2014,  2),
            (2014,  3),
            (2014,  4),
            (2014,  5),
            (2014,  6),
            (2014,  7),
            (2014,  8),
            (2014,  9),
            (2014, 10),
            (2014, 11),
            (2014, 12),
            (2015,  1),
            (2015,  2),
            (2015,  3),
            (2015,  4),
            (2015,  5),
            (2015,  6),
            (2015,  7),
            (2015,  8),
            (2015,  9),
            (2015, 10),
            (2015, 11),
            (2015, 12)],
           )

In [154]:
columns = pd.MultiIndex.from_product([['Bob','Sue','Yuya'], ['HR', 'Temp']])
columns

MultiIndex([( 'Bob',   'HR'),
            ( 'Bob', 'Temp'),
            ( 'Sue',   'HR'),
            ( 'Sue', 'Temp'),
            ('Yuya',   'HR'),
            ('Yuya', 'Temp')],
           )

In [155]:
pd.DataFrame(index=index, columns=columns)

Bob       Sue      Yuya     
          HR Temp   HR Temp   HR Temp
2013 1   NaN  NaN  NaN  NaN  NaN  NaN
     2   NaN  NaN  NaN  NaN  NaN  NaN
     3   NaN  NaN  NaN  NaN  NaN  NaN
     4   NaN  NaN  NaN  NaN  NaN  NaN
     5   NaN  NaN  NaN  NaN  NaN  NaN
     6   NaN  NaN  NaN  NaN  NaN  NaN
     7   NaN  NaN  NaN  NaN  NaN  NaN
     8   NaN  NaN  NaN  NaN  NaN  NaN
     9   NaN  NaN  NaN  NaN  NaN  NaN
     10  NaN  NaN  NaN  NaN  NaN  NaN
     11  NaN  NaN  NaN  NaN  NaN  NaN
     12  NaN  NaN  NaN  NaN  NaN  NaN
2014 1   NaN  NaN  NaN  NaN  NaN  NaN
     2   NaN  NaN  NaN  NaN  NaN  NaN
     3   NaN  NaN  NaN  NaN  NaN  NaN
     4   NaN  NaN  NaN  NaN  NaN  NaN
     5   NaN  NaN  NaN  NaN  NaN  NaN
     6   NaN  NaN  NaN  NaN  NaN  NaN
     7   NaN  NaN  NaN  NaN  NaN  NaN
     8   NaN  NaN  NaN  NaN  NaN  NaN
     9   NaN  NaN  NaN  NaN  NaN  NaN
     10  NaN  NaN  NaN  NaN  NaN  NaN
     11  NaN  NaN  NaN  NaN  NaN  NaN
     12  NaN  NaN  NaN  NaN  NaN  NaN
2015 1   NaN  NaN  NaN  NaN  NaN  NaN
     2   NaN  NaN  NaN  NaN  NaN  NaN
     3   NaN  NaN  NaN  NaN  NaN  NaN
     4   NaN  NaN  NaN  NaN  NaN  NaN
     5   NaN  NaN  NaN  NaN  NaN  NaN
     6   NaN  NaN  NaN  NaN  NaN  NaN
     7   NaN  NaN  NaN  NaN  NaN  NaN
     8   NaN  NaN  NaN  NaN  NaN  NaN
     9   NaN  NaN  NaN  NaN  NaN  NaN
     10  NaN  NaN  NaN  NaN  NaN  NaN
     11  NaN  NaN  NaN  NaN  NaN  NaN
     12  NaN  NaN  NaN  NaN  NaN  NaN

In [156]:
data = np.round(np.random.randn(36, 6),1)
data

array([[-1. ,  0.8, -0.5, -0.3, -0.2,  1.6],
       [ 0.5,  0.4, -0.7, -1.7,  0.4, -1.8],
       [ 1.4, -2.2,  0.7,  0.6,  0.2, -0.2],
       [ 0.1, -0.1, -0.5,  0.3,  1.7, -0.2],
       [-0.1, -1.6,  0.2, -1.4,  0.8,  0.4],
       [ 0.6,  0. ,  1.2,  0.5, -0.1,  1.7],
       [-0.2,  2.4,  1.4, -0.9,  0. , -0.8],
       [-1.3, -1.2, -0.7, -0.4, -0.3,  0.4],
       [ 0.9, -0.2,  0.5, -0.4, -0.3, -0.5],
       [ 0.9, -0.5,  1.2, -0.6,  0.4, -0.1],
       [-0.8, -3. , -0.1,  2.3, -1.2, -0.7],
       [ 0. , -1.9,  1.6, -0.7, -1.4, -1.2],
       [-0.5,  0.1,  2. , -1. ,  2. , -1.6],
       [-1.2, -1.3,  0.4, -0.1, -1. , -0.7],
       [-0.7, -0.1, -1.3, -0.6, -0.4, -0.4],
       [ 0.5, -0.4,  0.2, -1. ,  0.1,  0.2],
       [ 0.1, -2.2,  0.4,  1.1, -1.4, -0.4],
       [-0.6, -1.2,  0.8, -0.8, -0.7, -0.7],
       [ 0.4, -0.6, -0.7, -0.8, -0.1, -0.8],
       [-0.6,  0.2, -1. ,  0.7,  1. ,  0. ],
       [ 1.4, -1.5,  1. , -0.9, -0.1, -0.2],
       [ 2.3,  0.3,  1.4,  0.7,  0.3, -0.3],
       [ 0

In [157]:
data[:,::2] *= 10
data

array([[-10. ,   0.8,  -5. ,  -0.3,  -2. ,   1.6],
       [  5. ,   0.4,  -7. ,  -1.7,   4. ,  -1.8],
       [ 14. ,  -2.2,   7. ,   0.6,   2. ,  -0.2],
       [  1. ,  -0.1,  -5. ,   0.3,  17. ,  -0.2],
       [ -1. ,  -1.6,   2. ,  -1.4,   8. ,   0.4],
       [  6. ,   0. ,  12. ,   0.5,  -1. ,   1.7],
       [ -2. ,   2.4,  14. ,  -0.9,   0. ,  -0.8],
       [-13. ,  -1.2,  -7. ,  -0.4,  -3. ,   0.4],
       [  9. ,  -0.2,   5. ,  -0.4,  -3. ,  -0.5],
       [  9. ,  -0.5,  12. ,  -0.6,   4. ,  -0.1],
       [ -8. ,  -3. ,  -1. ,   2.3, -12. ,  -0.7],
       [  0. ,  -1.9,  16. ,  -0.7, -14. ,  -1.2],
       [ -5. ,   0.1,  20. ,  -1. ,  20. ,  -1.6],
       [-12. ,  -1.3,   4. ,  -0.1, -10. ,  -0.7],
       [ -7. ,  -0.1, -13. ,  -0.6,  -4. ,  -0.4],
       [  5. ,  -0.4,   2. ,  -1. ,   1. ,   0.2],
       [  1. ,  -2.2,   4. ,   1.1, -14. ,  -0.4],
       [ -6. ,  -1.2,   8. ,  -0.8,  -7. ,  -0.7],
       [  4. ,  -0.6,  -7. ,  -0.8,  -1. ,  -0.8],
       [ -6. ,   0.2, -10. ,   

In [158]:
data += 37
data

array([[27. , 37.8, 32. , 36.7, 35. , 38.6],
       [42. , 37.4, 30. , 35.3, 41. , 35.2],
       [51. , 34.8, 44. , 37.6, 39. , 36.8],
       [38. , 36.9, 32. , 37.3, 54. , 36.8],
       [36. , 35.4, 39. , 35.6, 45. , 37.4],
       [43. , 37. , 49. , 37.5, 36. , 38.7],
       [35. , 39.4, 51. , 36.1, 37. , 36.2],
       [24. , 35.8, 30. , 36.6, 34. , 37.4],
       [46. , 36.8, 42. , 36.6, 34. , 36.5],
       [46. , 36.5, 49. , 36.4, 41. , 36.9],
       [29. , 34. , 36. , 39.3, 25. , 36.3],
       [37. , 35.1, 53. , 36.3, 23. , 35.8],
       [32. , 37.1, 57. , 36. , 57. , 35.4],
       [25. , 35.7, 41. , 36.9, 27. , 36.3],
       [30. , 36.9, 24. , 36.4, 33. , 36.6],
       [42. , 36.6, 39. , 36. , 38. , 37.2],
       [38. , 34.8, 41. , 38.1, 23. , 36.6],
       [31. , 35.8, 45. , 36.2, 30. , 36.3],
       [41. , 36.4, 30. , 36.2, 36. , 36.2],
       [31. , 37.2, 27. , 37.7, 47. , 37. ],
       [51. , 35.5, 47. , 36.1, 36. , 36.8],
       [60. , 37.3, 51. , 37.7, 40. , 36.7],
       [38

In [169]:
health_data = pd.DataFrame(data,index=index, columns=columns)

In [170]:
health_data['Bob']

HR  Temp
2013 1   27.0  37.8
     2   42.0  37.4
     3   51.0  34.8
     4   38.0  36.9
     5   36.0  35.4
     6   43.0  37.0
     7   35.0  39.4
     8   24.0  35.8
     9   46.0  36.8
     10  46.0  36.5
     11  29.0  34.0
     12  37.0  35.1
2014 1   32.0  37.1
     2   25.0  35.7
     3   30.0  36.9
     4   42.0  36.6
     5   38.0  34.8
     6   31.0  35.8
     7   41.0  36.4
     8   31.0  37.2
     9   51.0  35.5
     10  60.0  37.3
     11  38.0  36.2
     12  60.0  37.1
2015 1   54.0  35.7
     2   49.0  37.6
     3   43.0  35.7
     4   29.0  38.1
     5   43.0  35.2
     6   49.0  38.2
     7   33.0  35.7
     8   33.0  35.1
     9   42.0  37.5
     10  40.0  36.6
     11  30.0  36.5
     12  41.0  37.1

In [171]:
# Multilndex 的 Series
pop

state       year
California  2000    3335234
            2010    5235423
New York    2000    3453253
            2010    4352542
Texas       2000    5346366
            2010    2342344
dtype: int64

In [172]:
pop['California',2000]

3335234

In [173]:
pop['California']

year
2000    3335234
2010    5235423
dtype: int64

In [174]:
pop.loc['California':'New York']

state       year
California  2000    3335234
            2010    5235423
New York    2000    3453253
            2010    4352542
dtype: int64

In [176]:
pop[:,2000]

state
California    3335234
New York      3453253
Texas         5346366
dtype: int64

In [179]:
pop[pop>4000000]

state       year
California  2010    5235423
New York    2010    4352542
Texas       2000    5346366
dtype: int64

In [180]:
# Multilndex 的 Dataframe
health_data['Bob', 'HR']

2013  1     27.0
      2     42.0
      3     51.0
      4     38.0
      5     36.0
      6     43.0
      7     35.0
      8     24.0
      9     46.0
      10    46.0
      11    29.0
      12    37.0
2014  1     32.0
      2     25.0
      3     30.0
      4     42.0
      5     38.0
      6     31.0
      7     41.0
      8     31.0
      9     51.0
      10    60.0
      11    38.0
      12    60.0
2015  1     54.0
      2     49.0
      3     43.0
      4     29.0
      5     43.0
      6     49.0
      7     33.0
      8     33.0
      9     42.0
      10    40.0
      11    30.0
      12    41.0
Name: (Bob, HR), dtype: float64

In [182]:
health_data

Bob         Sue        Yuya      
           HR  Temp    HR  Temp    HR  Temp
2013 1   27.0  37.8  32.0  36.7  35.0  38.6
     2   42.0  37.4  30.0  35.3  41.0  35.2
     3   51.0  34.8  44.0  37.6  39.0  36.8
     4   38.0  36.9  32.0  37.3  54.0  36.8
     5   36.0  35.4  39.0  35.6  45.0  37.4
     6   43.0  37.0  49.0  37.5  36.0  38.7
     7   35.0  39.4  51.0  36.1  37.0  36.2
     8   24.0  35.8  30.0  36.6  34.0  37.4
     9   46.0  36.8  42.0  36.6  34.0  36.5
     10  46.0  36.5  49.0  36.4  41.0  36.9
     11  29.0  34.0  36.0  39.3  25.0  36.3
     12  37.0  35.1  53.0  36.3  23.0  35.8
2014 1   32.0  37.1  57.0  36.0  57.0  35.4
     2   25.0  35.7  41.0  36.9  27.0  36.3
     3   30.0  36.9  24.0  36.4  33.0  36.6
     4   42.0  36.6  39.0  36.0  38.0  37.2
     5   38.0  34.8  41.0  38.1  23.0  36.6
     6   31.0  35.8  45.0  36.2  30.0  36.3
     7   41.0  36.4  30.0  36.2  36.0  36.2
     8   31.0  37.2  27.0  37.7  47.0  37.0
     9   51.0  35.5  47.0  36.1  36.0  36.8
     10  60.0  37.3  51.0  37.7  40.0  36.7
     11  38.0  36.2  33.0  38.6  23.0  36.7
     12  60.0  37.1  24.0  36.5  24.0  37.4
2015 1   54.0  35.7  36.0  36.4  58.0  36.3
     2   49.0  37.6  32.0  36.7  35.0  36.4
     3   43.0  35.7  26.0  37.0  49.0  37.4
     4   29.0  38.1  39.0  36.2  44.0  36.9
     5   43.0  35.2  38.0  38.0  31.0  37.4
     6   49.0  38.2  66.0  36.7  42.0  38.2
     7   33.0  35.7  41.0  36.5  45.0  36.2
     8   33.0  35.1  36.0  36.7  41.0  36.0
     9   42.0  37.5  43.0  37.6  47.0  36.8
     10  40.0  36.6  50.0  37.0  32.0  39.3
     11  30.0  36.5  12.0  37.8  53.0  36.3
     12  41.0  37.1  36.0  36.2  51.0  38.8

In [185]:
health_data.iloc[:2,:1]

Bob
          HR
2013 1  27.0
     2  42.0

In [189]:
health_data.loc[(2013,2), ('Bob','HR')]

42.0

In [193]:
idx = pd.IndexSlice
health_data.loc[idx[:,1], idx[:,'HR']]

Bob   Sue  Yuya
          HR    HR    HR
2013 1  27.0  32.0  35.0
2014 1  32.0  57.0  57.0
2015 1  54.0  36.0  58.0

In [211]:
#重排列多重索引 
index = pd.MultiIndex.from_product([list('ac2'),list('12')])
data = pd.Series(np.random.rand(6), index=index)
data.index.names = ['char', 'int']
data

char  int
a     1      0.187515
      2      0.443899
c     1      0.923616
      2      0.459004
2     1      0.749496
      2      0.862746
dtype: float64

In [212]:
data['a':'c'] #未經排序的多重索引 slice時會出錯

UnsortedIndexError: 'Key length (1) was greater than MultiIndex lexsort depth (0)'

In [222]:
data = data.sort_index()

In [226]:
data['a':'c']

char  int
a     1      0.187515
      2      0.443899
c     1      0.923616
      2      0.459004
dtype: float64

In [232]:
#索引的stacking和unstacking
pop

state       year
California  2000    3335234
            2010    5235423
New York    2000    3453253
            2010    4352542
Texas       2000    5346366
            2010    2342344
dtype: int64

In [238]:
pop.unstack(level=0)

state  California  New York    Texas
year                                
2000      3335234   3453253  5346366
2010      5235423   4352542  2342344

In [239]:
pop.unstack(level=1)

year           2000     2010
state                       
California  3335234  5235423
New York    3453253  4352542
Texas       5346366  2342344

In [240]:
pop.unstack().stack()

state       year
California  2000    3335234
            2010    5235423
New York    2000    3453253
            2010    4352542
Texas       2000    5346366
            2010    2342344
dtype: int64

In [243]:
#把索引標籤轉換成欄
pop_flat = pop.reset_index(name='population')
pop_flat

state  year  population
0  California  2000     3335234
1  California  2010     5235423
2    New York  2000     3453253
3    New York  2010     4352542
4       Texas  2000     5346366
5       Texas  2010     2342344

In [244]:
#把dataframe變成多層索引
pop_flat.set_index(['state','year'])

population
state      year            
California 2000     3335234
           2010     5235423
New York   2000     3453253
           2010     4352542
Texas      2000     5346366
           2010     2342344

In [249]:
#多重索引聚合處理
health_data.index.names = ['year', 'visit']
health_data

Bob         Sue        Yuya      
              HR  Temp    HR  Temp    HR  Temp
year visit                                    
2013 1      27.0  37.8  32.0  36.7  35.0  38.6
     2      42.0  37.4  30.0  35.3  41.0  35.2
     3      51.0  34.8  44.0  37.6  39.0  36.8
     4      38.0  36.9  32.0  37.3  54.0  36.8
     5      36.0  35.4  39.0  35.6  45.0  37.4
     6      43.0  37.0  49.0  37.5  36.0  38.7
     7      35.0  39.4  51.0  36.1  37.0  36.2
     8      24.0  35.8  30.0  36.6  34.0  37.4
     9      46.0  36.8  42.0  36.6  34.0  36.5
     10     46.0  36.5  49.0  36.4  41.0  36.9
     11     29.0  34.0  36.0  39.3  25.0  36.3
     12     37.0  35.1  53.0  36.3  23.0  35.8
2014 1      32.0  37.1  57.0  36.0  57.0  35.4
     2      25.0  35.7  41.0  36.9  27.0  36.3
     3      30.0  36.9  24.0  36.4  33.0  36.6
     4      42.0  36.6  39.0  36.0  38.0  37.2
     5      38.0  34.8  41.0  38.1  23.0  36.6
     6      31.0  35.8  45.0  36.2  30.0  36.3
     7      41.0  36.4  30.0  36.2  36.0  36.2
     8      31.0  37.2  27.0  37.7  47.0  37.0
     9      51.0  35.5  47.0  36.1  36.0  36.8
     10     60.0  37.3  51.0  37.7  40.0  36.7
     11     38.0  36.2  33.0  38.6  23.0  36.7
     12     60.0  37.1  24.0  36.5  24.0  37.4
2015 1      54.0  35.7  36.0  36.4  58.0  36.3
     2      49.0  37.6  32.0  36.7  35.0  36.4
     3      43.0  35.7  26.0  37.0  49.0  37.4
     4      29.0  38.1  39.0  36.2  44.0  36.9
     5      43.0  35.2  38.0  38.0  31.0  37.4
     6      49.0  38.2  66.0  36.7  42.0  38.2
     7      33.0  35.7  41.0  36.5  45.0  36.2
     8      33.0  35.1  36.0  36.7  41.0  36.0
     9      42.0  37.5  43.0  37.6  47.0  36.8
     10     40.0  36.6  50.0  37.0  32.0  39.3
     11     30.0  36.5  12.0  37.8  53.0  36.3
     12     41.0  37.1  36.0  36.2  51.0  38.8

In [259]:
health_data.columns.names = ['subject', 'type']
health_data

subject      Bob         Sue        Yuya      
type          HR  Temp    HR  Temp    HR  Temp
year visit                                    
2013 1      27.0  37.8  32.0  36.7  35.0  38.6
     2      42.0  37.4  30.0  35.3  41.0  35.2
     3      51.0  34.8  44.0  37.6  39.0  36.8
     4      38.0  36.9  32.0  37.3  54.0  36.8
     5      36.0  35.4  39.0  35.6  45.0  37.4
     6      43.0  37.0  49.0  37.5  36.0  38.7
     7      35.0  39.4  51.0  36.1  37.0  36.2
     8      24.0  35.8  30.0  36.6  34.0  37.4
     9      46.0  36.8  42.0  36.6  34.0  36.5
     10     46.0  36.5  49.0  36.4  41.0  36.9
     11     29.0  34.0  36.0  39.3  25.0  36.3
     12     37.0  35.1  53.0  36.3  23.0  35.8
2014 1      32.0  37.1  57.0  36.0  57.0  35.4
     2      25.0  35.7  41.0  36.9  27.0  36.3
     3      30.0  36.9  24.0  36.4  33.0  36.6
     4      42.0  36.6  39.0  36.0  38.0  37.2
     5      38.0  34.8  41.0  38.1  23.0  36.6
     6      31.0  35.8  45.0  36.2  30.0  36.3
     7      41.0  36.4  30.0  36.2  36.0  36.2
     8      31.0  37.2  27.0  37.7  47.0  37.0
     9      51.0  35.5  47.0  36.1  36.0  36.8
     10     60.0  37.3  51.0  37.7  40.0  36.7
     11     38.0  36.2  33.0  38.6  23.0  36.7
     12     60.0  37.1  24.0  36.5  24.0  37.4
2015 1      54.0  35.7  36.0  36.4  58.0  36.3
     2      49.0  37.6  32.0  36.7  35.0  36.4
     3      43.0  35.7  26.0  37.0  49.0  37.4
     4      29.0  38.1  39.0  36.2  44.0  36.9
     5      43.0  35.2  38.0  38.0  31.0  37.4
     6      49.0  38.2  66.0  36.7  42.0  38.2
     7      33.0  35.7  41.0  36.5  45.0  36.2
     8      33.0  35.1  36.0  36.7  41.0  36.0
     9      42.0  37.5  43.0  37.6  47.0  36.8
     10     40.0  36.6  50.0  37.0  32.0  39.3
     11     30.0  36.5  12.0  37.8  53.0  36.3
     12     41.0  37.1  36.0  36.2  51.0  38.8

In [261]:
data_mean = health_data.mean(level=['year'])
data_mean

subject        Bob                   Sue             Yuya           
type            HR       Temp         HR       Temp    HR       Temp
year                                                                
2013     37.833333  36.408333  40.583333  36.775000  37.0  36.883333
2014     39.916667  36.383333  38.250000  36.866667  34.5  36.600000
2015     40.500000  36.583333  37.916667  36.900000  44.0  37.166667

In [263]:
data_mean.mean(axis=1, level='subject')

subject        Bob        Sue       Yuya
year                                    
2013     37.120833  38.679167  36.941667
2014     38.150000  37.558333  35.550000
2015     38.541667  37.408333  40.583333

In [264]:
#資料集合併
import numpy as np
import pandas as pd

In [270]:
def make_df(cols, ind):
    data = {c: [str(c) + str(i) for i in ind] for c in cols}
    return pd.DataFrame(data, ind)

In [276]:
make_df('ABC', range(4))

A   B   C
0  A0  B0  C0
1  A1  B1  C1
2  A2  B2  C2
3  A3  B3  C3

In [284]:
ser1 = pd.Series(['a','b','c'], index=[1,2,3])
ser2 = pd.Series(['d','e','f'], index=[4,5,6])
pd.concat([ser1, ser2])

1    a
2    b
3    c
4    d
5    e
6    f
dtype: object

In [291]:
df1 = make_df('AB',[1,2])
df2 = make_df('AB',[3,4])
print(df1)
print(df2)
print(pd.concat([df1, df2]))

    A   B
1  A1  B1
2  A2  B2
    A   B
3  A3  B3
4  A4  B4
    A   B
1  A1  B1
2  A2  B2
3  A3  B3
4  A4  B4


In [297]:
#重複的索引
x = make_df('AB',[0, 1])
y = make_df('AB',[2, 3])
y.index = x.index
print(x)
print(y)
print(pd.concat([x, y]))

    A   B
0  A0  B0
1  A1  B1
    A   B
0  A2  B2
1  A3  B3
    A   B
0  A0  B0
1  A1  B1
0  A2  B2
1  A3  B3


In [301]:
z = pd.concat([x, y])
z.loc[0]

A   B
0  A0  B0
0  A2  B2

In [304]:
pd.concat([x, y], verify_integrity=True)

ValueError: Indexes have overlapping values: Int64Index([0, 1], dtype='int64')

In [305]:
pd.concat([x, y], ignore_index=True)

A   B
0  A0  B0
1  A1  B1
2  A2  B2
3  A3  B3

In [308]:
pd.concat([x, y], keys=['x','y'])

A   B
x 0  A0  B0
  1  A1  B1
y 0  A2  B2
  1  A3  B3

In [310]:
#用join串接
df5 = make_df('ABC',[1, 2])
df6 = make_df('BCD',[3, 4])
pd.concat([df5, df6])

C:\Users\9Suser\Anaconda3\lib\site-packages\ipykernel_launcher.py:4: FutureWarning: Sorting because non-concatenation axis is not aligned. A future version
of pandas will change to not sort by default.

To accept the future behavior, pass 'sort=False'.

To retain the current behavior and silence the warning, pass 'sort=True'.

  after removing the cwd from sys.path.


A   B   C    D
1   A1  B1  C1  NaN
2   A2  B2  C2  NaN
3  NaN  B3  C3   D3
4  NaN  B4  C4   D4

In [313]:
pd.concat([df5, df6], join = 'inner') #inner join 

B   C
1  B1  C1
2  B2  C2
3  B3  C3
4  B4  C4

In [315]:
pd.concat([df5, df6], join_axes=[df5.columns]) #left join

C:\Users\9Suser\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: FutureWarning: The join_axes-keyword is deprecated. Use .reindex or .reindex_like on the result to achieve the same functionality.
  """Entry point for launching an IPython kernel.


A   B   C
1   A1  B1  C1
2   A2  B2  C2
3  NaN  B3  C3
4  NaN  B4  C4

In [319]:
#append = concat
aaa = df1.append(df2)
bbb = pd.concat([df1,df2])
aaa == bbb

A     B
1  True  True
2  True  True
3  True  True
4  True  True

In [327]:
#Merge and join
#一對一join
df1 = pd.DataFrame({'employee': ['Bob', 'Jake', 'Lisa', 'Sue', 'ddd'], 'group': ['Accounting', 'Engineering', 'Engineering', 'HR','ddd']})
df2 = pd.DataFrame({'employee': ['Bob', 'Jake', 'Lisa', 'Sue'], 'hire_date': [2004, 2008, 2012, 2014]})
print(df1)
print(df2)


  employee        group
0      Bob   Accounting
1     Jake  Engineering
2     Lisa  Engineering
3      Sue           HR
4      ddd          ddd
  employee  hire_date
0      Bob       2004
1     Jake       2008
2     Lisa       2012
3      Sue       2014


In [339]:
df3 = pd.merge(df2, df1)
df3

employee  hire_date        group
0      Bob       2004   Accounting
1     Jake       2008  Engineering
2     Lisa       2012  Engineering
3      Sue       2014           HR

In [338]:
pd.merge(df2, df1, how='outer')

employee  hire_date        group
0      Bob     2004.0   Accounting
1     Jake     2008.0  Engineering
2     Lisa     2012.0  Engineering
3      Sue     2014.0           HR
4      ddd        NaN          ddd

In [332]:
pd.concat([df1, df2], join='inner', axis =1 )

employee        group employee  hire_date
0      Bob   Accounting      Bob       2004
1     Jake  Engineering     Jake       2008
2     Lisa  Engineering     Lisa       2012
3      Sue           HR      Sue       2014

In [344]:
#多對一join
df4 = pd.DataFrame({'group':['Accounting', 'Engineering', 'HR'], 'supervisor':['Carly', 'Guido', 'Steve']})
df4

group supervisor
0   Accounting      Carly
1  Engineering      Guido
2           HR      Steve

In [345]:
pd.merge(df3, df4)

employee  hire_date        group supervisor
0      Bob       2004   Accounting      Carly
1     Jake       2008  Engineering      Guido
2     Lisa       2012  Engineering      Guido
3      Sue       2014           HR      Steve

In [352]:
#多對多join
df5 = pd.DataFrame({'group': ['Accounting', 'Accounting', 'Engineering', 'Engineering', 'HR', 'HR'],
                    'skills': ['math', 'spreadsheets', 'coding', 'linux', 'spreadsheets', 'organization']})
print(df1)
print(df5)

  employee        group
0      Bob   Accounting
1     Jake  Engineering
2     Lisa  Engineering
3      Sue           HR
4      ddd          ddd
         group        skills
0   Accounting          math
1   Accounting  spreadsheets
2  Engineering        coding
3  Engineering         linux
4           HR  spreadsheets
5           HR  organization


In [353]:
pd.merge(df1, df5)

employee        group        skills
0      Bob   Accounting          math
1      Bob   Accounting  spreadsheets
2     Jake  Engineering        coding
3     Jake  Engineering         linux
4     Lisa  Engineering        coding
5     Lisa  Engineering         linux
6      Sue           HR  spreadsheets
7      Sue           HR  organization

In [354]:
#Merge 參數
#on
print(df1)
print(df2)
print(pd.merge(df1, df2, on='employee'))

  employee        group
0      Bob   Accounting
1     Jake  Engineering
2     Lisa  Engineering
3      Sue           HR
4      ddd          ddd
  employee  hire_date
0      Bob       2004
1     Jake       2008
2     Lisa       2012
3      Sue       2014
  employee        group  hire_date
0      Bob   Accounting       2004
1     Jake  Engineering       2008
2     Lisa  Engineering       2012
3      Sue           HR       2014


In [357]:
#left_on right_on
df3_2 = pd.DataFrame({'name': ['Bob', 'Jake', 'Lisa', 'Sue'],
                      'salary': [70000, 43333, 55555, 11111]})
print(df1)
print(df3_2)
print(pd.merge(df1, df3_2, left_on='employee', right_on='name'))

  employee        group
0      Bob   Accounting
1     Jake  Engineering
2     Lisa  Engineering
3      Sue           HR
4      ddd          ddd
   name  salary
0   Bob   70000
1  Jake   43333
2  Lisa   55555
3   Sue   11111
  employee        group  name  salary
0      Bob   Accounting   Bob   70000
1     Jake  Engineering  Jake   43333
2     Lisa  Engineering  Lisa   55555
3      Sue           HR   Sue   11111


In [360]:
#刪除多餘欄位
pd.merge(df1, df3_2, left_on='employee', right_on='name').drop('name', axis=1)

employee        group  salary
0      Bob   Accounting   70000
1     Jake  Engineering   43333
2     Lisa  Engineering   55555
3      Sue           HR   11111

In [364]:
#left_index right_index

df1a = df1.set_index('employee')
df2a = df2.set_index('employee')
print(df1a)
print(df2a)

                group
employee             
Bob        Accounting
Jake      Engineering
Lisa      Engineering
Sue                HR
ddd               ddd
          hire_date
employee           
Bob            2004
Jake           2008
Lisa           2012
Sue            2014


In [369]:
pd.merge(df1a, df2a, left_index=True, right_index=True)

group  hire_date
employee                        
Bob        Accounting       2004
Jake      Engineering       2008
Lisa      Engineering       2012
Sue                HR       2014

In [371]:
df1a.join(df2a)

group  hire_date
employee                        
Bob        Accounting     2004.0
Jake      Engineering     2008.0
Lisa      Engineering     2012.0
Sue                HR     2014.0
ddd               ddd        NaN

In [373]:
#混合使用
print(df1a)
print(df3_2)
print(pd.merge(df1a, df3_2, left_index=True, right_on='name'))

                group
employee             
Bob        Accounting
Jake      Engineering
Lisa      Engineering
Sue                HR
ddd               ddd
   name  salary
0   Bob   70000
1  Jake   43333
2  Lisa   55555
3   Sue   11111
         group  name  salary
0   Accounting   Bob   70000
1  Engineering  Jake   43333
2  Engineering  Lisa   55555
3           HR   Sue   11111


In [11]:
#join運算
df6 = pd.DataFrame({'name': ['Peter', 'Paul', 'Mary'],
                    'food': ['fish', 'beans', 'bread']},
                   columns=['name', 'food'])
df7 = pd.DataFrame({'name': ['Mary', 'Joseph'],
                    'drink': ['wine', 'beer']},
                   columns=['name', 'drink'])
print(df6)
print(df7)
print(pd.merge(df6, df7))

    name   food
0  Peter   fish
1   Paul  beans
2   Mary  bread
     name drink
0    Mary  wine
1  Joseph  beer
   name   food drink
0  Mary  bread  wine


In [12]:
pd.merge(df6, df7, how='inner')

name   food drink
0  Mary  bread  wine

In [13]:
pd.merge(df6, df7, how='outer')

name   food drink
0   Peter   fish   NaN
1    Paul  beans   NaN
2    Mary  bread  wine
3  Joseph    NaN  beer

In [14]:
pd.merge(df6, df7, how='left')

name   food drink
0  Peter   fish   NaN
1   Paul  beans   NaN
2   Mary  bread  wine

In [15]:
pd.merge(df6, df7, how='right')

name   food drink
0    Mary  bread  wine
1  Joseph    NaN  beer

In [19]:
df8 = pd.DataFrame({'name': ['Bob', 'Jake', 'Lisa', 'Sue'],
                    'rank': [1, 2, 3, 4]})
df9 = pd.DataFrame({'name': ['Bob', 'Jake', 'Lisa', 'Sue'],
                    'rank': [3, 1, 4, 2]})
print(df8)
print(df9)
print(pd.merge(df8, df9, on='name'))

   name  rank
0   Bob     1
1  Jake     2
2  Lisa     3
3   Sue     4
   name  rank
0   Bob     3
1  Jake     1
2  Lisa     4
3   Sue     2
   name  rank_x  rank_y
0   Bob       1       3
1  Jake       2       1
2  Lisa       3       4
3   Sue       4       2


In [25]:
pd.merge(df8, df9, on='name', suffixes=['_L','_K'])

name  rank_L  rank_K
0   Bob       1       3
1  Jake       2       1
2  Lisa       3       4
3   Sue       4       2